### ISSUE TITLE
IP Adress has changed - Now HA can't find my Intex Spa

### ISSUE THREAD

**Issue by grojaben** [mathieu-mp/homeassistant-intex-spa#116]
Hello,
yesterday my router changed the IP address for my Intex pool after an update. Where can I store the new IP address for the Home Assistant component? When I add the pool it works. However, I would then have to add new entities to all automations. Can someone help me?

**Comment by mathieu-mp** [comment]
Hello,
Two ways to do this:
1- On your router, set a static DHCP mapping for your spa, so that its IP is back to the one you used in Home Assistant, and it doesn't change any more.
2- Delete then re-add the device through the Intex Spa integration, then make sure the new names of the entities exactly match the previous ones.
With both solutions, you don't have to change your automations.

**Comment by grojaben** [comment]
Perfect. Things are going great now. And I fixed the current IP address in the router. Thank you for the quick help
